[workspace]
channels = ["conda-forge"]
name = "complaints"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-kernel = "python -m ipykernel install --user --name <kernel name> --display-name <kernel name>"


[dependencies]
numpy = ">=2.3.3,<3"
jupyter = ">=1.1.1,<2"
notebook = ">=7.4.7,<8"
ipykernel = ">=7.1.0,<8"
pip = ">=25.2,<26"
pandas = ">=2.3.3,<3"

[pypi-dependencies]
llamabot = ">=0.13.8, <0.14"
